repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        entry: black
        language_version: python
        types: [python]
        args: [--line-length=88]
        exclude: ^dist/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        entry: mypy
        language_version: python
        types: [python]
        args: [--ignore-missing-imports, --explicit-package-bases, --namespace-packages, --exclude, 'protobufs/*', --follow-imports, 'skip']
        exclude: 'protobufs/.*'

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        entry: ruff check
        language_version: python
        types: [python]
