repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.7.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
        types: [python]
        args: [--check]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        types: [python]
        args: [--strict]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        types: [python]